baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'DD20 SRD'
theme = 'hugo-book'
[params]
BookTheme = 'dark'
BookToC = false
BookSection = '*'
BookSearch = false
[markup.goldmark.renderer]
unsafe = true