baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Double Down SRD'
theme = 'hugo-book'
[params]
BookTheme = 'dark'
BookToC = false
BookSection = '*'
[markup.goldmark.renderer]
unsafe = true