baseURL = 'https://doubledown.help'
languageCode = 'en-us'
title = 'DD20 SRD'
theme = 'hugo-book'
[params]
BookTheme = 'dark'
BookToC = true
BookSection = '*'
BookSearch = false
[markup.goldmark.renderer]
unsafe = true